Update dev env scripts

diff --git a/.hooks/check-submodules b/.hooks/check-submodules
--- a/.hooks/check-submodules
+++ b/.hooks/check-submodules
@@ -1,7 +1,7 @@
 #!/bin/bash
+# shellcheck disable=SC2086
 
-# Debugging
-# set -x
+set -euo pipefail
 
 ### ----------------------------------------------------------------------
 txtred='\033[0;31m'       # red
@@ -16,11 +16,10 @@ txtrst='\033[0m'          # Text reset
 # regex
 SUBMODULE_REGEX_STATUS="([\+-uU[:space:]])([^[:space:]]*) ([^[:space:]]*)( ([^[:space:]]*))?"
 SUBMODULE_REGEX_MODULE="path = (.*)"
-GIT_REGEX_DIFF_COMMIT=".*commit (.*)"
 
 # ------------------------------
 print_error() {
-  echo -e "${bldred}$1${txtrst}"
+  echo -e "${bldred}$1${txtrst}" 2>/dev/stderr
 }
 
 # ------------------------------
@@ -45,21 +44,26 @@ parse_git_branch() {
 
 # ------------------------------
 find_submodule_remote_ref() {
-  local l_remote_ref=`git rev-parse --remotes=*$1`
+  local l_remote_ref
+  #if git fetch origin main ; then
+  #  print_error "unable to fetch"
+  #fi
+  l_remote_ref=$(git ls-remote --exit-code --ref -b origin main | cut -f 1)
   echo ${l_remote_ref}
   return 0
 }
 
 # ------------------------------
 # $1 = path
+# $2 = the local revision that is being pushed to the remote
 find_submodule_commit_hash() {
-  local rev=${PRE_COMMIT_TO_REF}
+  local rev=$2
   if [ -z "$rev" ]; then
     rev=HEAD
   fi
-  local l_br=`git ls-tree ${rev} -- $1 | cut -d ' ' -f 3`
-  local commit=$(echo $l_br | cut -d $'\t' -f 1)
-  echo $commit
+  local l_br
+  l_br=$(git ls-tree --object-only ${rev} -- $1)
+  echo $l_br
   return 0
 }
 
@@ -72,67 +76,47 @@ check_submodule_is_pushed() {
   local l_hash=$1
   local l_path=$2
 
-  done_processing=
-  while read line
-  do
-    if [[ "$line" =~ $SUBMODULE_REGEX_MODULE ]]; then
-      if [[ ${BASH_REMATCH[1]} == ${l_path} ]]; then
-        diffed_submodule=`find_submodule_commit_hash ${l_path}`
-        if [[ "$?" -eq 0 ]]; then
-          pushd . > /dev/null
-          # echo "let's go to submodule folder... [${BASH_REMATCH[1]}]"
-          cd ${BASH_REMATCH[1]}
-          local l_branch=$(parse_git_branch)
-          # echo "BRANCH is <<${l_branch}>>"
-          local l_remote_ref=$(find_submodule_remote_ref ${l_branch})
-          # echo "remote REF is <<${l_remote_ref}>>"
-          popd > /dev/null
-
-          # finally!!!!!
-          if [[ $l_hash == $l_remote_ref ]]; then
-            print_success "All is good with this submodule..."
-            return 0
-          else
-            echo " "
-            print_error "Stop! Pre-commit condition failed."
-            echo "Did you forget to push submodule [$l_path] to remote?"
-            echo "Cannot proceed until you do so."
-            print_warning_with_title "Remote HASH" ${l_remote_ref}
-            print_warning_with_title "Local HASH." ${l_hash}
-            echo " "
-            return -1
-          fi
-        # else
-          # should we just skip instead of break?
-          # print_error ">> [$l_path] - No commit HASH found..."
-          # return -1
-          # noop
-        fi
-      fi
-    # else
-      # print_error "NOT submodule line... continue"
-      # return -1
+  while read -r line ; do
+    if [[ ! "$line" =~ $SUBMODULE_REGEX_MODULE ]]; then
+      continue
     fi
-  done < ${SUBMODULE_CONFIG_FILE}
+    if [[ ! ${BASH_REMATCH[1]} == "${l_path}" ]]; then
+      continue
+    fi
+    local target_commit
+    target_commit=$(find_submodule_commit_hash ${l_path} ${PRE_COMMIT_TO_REF})
 
-  if [[ -z done_processing ]]; then
-    print_error ">> Could not process submodule..."
-    return -1  #signal error
-  fi
+    pushd . > /dev/null
+    cd ${BASH_REMATCH[1]} || exit 1
+    local l_remote_ref
+    l_remote_ref=$(find_submodule_remote_ref)
+    if git merge-base --is-ancestor "$target_commit" "$l_remote_ref" ; then
+      print_success "  All is good with this submodule..."
+      return 0
+    else
+      print_error "Stop! Pre-commit condition failed."
+      echo "Did you forget to push submodule [$l_path] to remote?"
+      echo "Cannot proceed until you do so."
+
+      print_warning_with_title "Checking ${PRE_COMMIT_FROM_REF}..${PRE_COMMIT_TO_REF}"
+      print_warning_with_title "  Submodule remote ref" ${l_remote_ref}
+      print_warning_with_title "  Submodule local ref" ${l_hash}
+      return 1
+    fi
+  done < "${SUBMODULE_CONFIG_FILE}"
 }
 
 ### ----------------------------------------------------------------------
 ### MAIN
 ### ----------------------------------------------------------------------
 
-PROJECT_ROOT=`git rev-parse --git-dir`/..
-# echo "root is ${PROJECT_ROOT}"
+PROJECT_ROOT=$(realpath "$(git rev-parse --git-dir)"/..)
 
 # ------------------------------
 # exit if nothing to do here...
 SUBMODULE_CONFIG_FILE=${PROJECT_ROOT}/.gitmodules
 if [[ ! -f ${SUBMODULE_CONFIG_FILE} ]]; then
-  # echo "NO SUBMODULE -- exit"
+  echo "No submodules found in .gitmodules"
   exit 0
 fi
 
@@ -142,41 +126,37 @@ echo "Checking submodules..."
 IFS=$'\x0A'$'\x0D'
 #save initial dir
 pushd . > /dev/null
-cd ${PROJECT_ROOT}
+cd ${PROJECT_ROOT} || exit
 
 FAILED=0
-# loop through all submodules
-git_submodules=`git submodule`
-for l in $git_submodules
-do
-  if [[ "$l" =~ $SUBMODULE_REGEX_STATUS ]]; then
-    status=${BASH_REMATCH[1]}
-    hash=${BASH_REMATCH[2]}
-    path=${BASH_REMATCH[3]}
-    branch=${BASH_REMATCH[5]}
 
-    # if [[ $status =~ " " ]]; then
-    #   print_success "  Submodule [$path] ... OK"
-    if [[ $status == "-" ]]; then
-      print_error "  Submodule [$path] ... NOT initialized"
+# loop through all submodules
+git_submodules=$(git submodule)
+for l in $git_submodules ; do
+  if [[ ! "$l" =~ $SUBMODULE_REGEX_STATUS ]]; then
+    continue
+  fi
+  status=${BASH_REMATCH[1]}
+  hash=${BASH_REMATCH[2]}
+  path=${BASH_REMATCH[3]}
+  branch=${BASH_REMATCH[5]}
+
+  echo "[$path]"
+  if [[ $status == "-" ]]; then
+    print_error "  Submodule [$path] not initialized"
+    exit 1
+  else
+    if check_submodule_is_pushed ${hash} ${path}; then
+      print_success "  Submodule [$path] OK"
     else
-      # echo "submodule changed!!! let's check revisions"
-      success=`check_submodule_is_pushed ${hash} ${path}`
-      if [[ "$?" -eq 0 ]]; then
-        print_success "  Submodule [$path] ... OK"
-      else
-        IFS=$''
-        print_error "  Submodule [$path] ... FAILED"
-        echo $success
-        FAILED=1
-        exit 1 # break as soon as submodule fails
-      fi
+      IFS=$''
+      print_error "  Submodule [$path] FAILED"
+      FAILED=1
     fi
   fi
 done
 
 # go back to original folder
-popd > /dev/null
+popd > /dev/null || exit
 
-echo "returning state $FAILED"
 exit $FAILED
