CI: Fix reviewdog run

diff --git a/.github/workflows/reviewdog.yml b/.github/workflows/reviewdog.yml
--- a/.github/workflows/reviewdog.yml
+++ b/.github/workflows/reviewdog.yml
@@ -11,8 +11,6 @@ jobs:
       checks: write
       contents: read
       pull-requests: write
-    env:
-      UV_CACHE_DIR: /tmp/.uv-cache
     steps:
       - uses: actions/checkout@v4
         with:
@@ -21,24 +19,33 @@ jobs:
 
       - name: Install uv
         uses: astral-sh/setup-uv@v5
+        with:
+          enable-cache: true
+          cache-dependency-glob: |
+            requirements-lint.txt
+            requirements-kausal.txt
+            requirements.txt
+            pyproject.toml
 
       - name: Setup cache
         uses: actions/cache@v4
-        id: cache
         with:
           path: |
-            ${{ env.UV_CACHE_DIR }}
             .mypy_cache
-          key: ${{ runner.os }}-${{ hashFiles('requirements-lint.txt', 'requirements-kausal.txt', 'requirements.txt') }}
-          restore-keys: |
-            ${{ runner.os }}-${{ hashFiles('requirements-lint.txt', 'requirements-kausal.txt', 'requirements.txt') }}
-            ${{ runner.os }}
+          key: ${{ runner.os }}-${{ hashFiles('requirements-lint.txt', 'requirements-kausal.txt', 'requirements.txt', 'pyproject.toml') }}
 
       - name: Set up Python
         run: uv python install
 
-      - name: Install deb dependencies
-        run: sudo apt update && sudo apt install --no-install-recommends -y libproj-dev gdal-bin
+      # - uses: awalsh128/cache-apt-pkgs-action@latest
+      #   with:
+      #     packages: libproj-dev libgdal-dev
+      #     version: 1.0
+      #     execute_install_scripts: true
+
+      - name: Install gdal dependencies
+        run: |
+          sudo apt-get update && sudo apt-get install --no-install-recommends -y libproj-dev libgdal-dev
 
       - name: Install Python dependencies
         env:
@@ -47,17 +54,6 @@ jobs:
           uv venv
           . .venv/bin/activate
           uv pip install -r requirements-lint.txt -r requirements.txt -r requirements-kausal.txt --extra-index-url "$EXTRA_PYPI_INDEX"
-
-      - name: Minimize uv cache
-        run: uv cache prune --ci
-
-      - name: Save cache
-        uses: actions/cache/save@v4
-        if: ${{ ! steps.cache.outputs.cache-hit }}
-        with:
-          path: |
-            ${{ env.UV_CACHE_DIR }}
-          key: ${{ runner.os }}-${{ hashFiles('requirements-lint.txt', 'requirements-kausal.txt', 'requirements.txt') }}
 
       - name: Get push diff
         if: github.event_name == 'push' && github.event.before
@@ -84,7 +80,19 @@ jobs:
           REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           . .venv/bin/activate
-          reviewdog -reporter=local -fail-on-error -diff "cat ${{ runner.temp }}/changes.diff"
+          REVIEWDOG_ARGS="-reporter=github-check -fail-level=error -diff 'cat ${{ runner.temp }}/changes.diff'"
+          echo running reviewdog
+          reviewdog -runners=ruff -filter-mode=added $REVIEWDOG_ARGS
+          echo running mypy
+          mypy . > ${{ runner.temp }}/mypy-output.txt || mypy_exit=$?
+          if [[ $mypy_exit -ne 0 && $mypy_exit -ne 1 ]]; then
+            echo "mypy failed with exit code $mypy_exit"
+            cat ${{ runner.temp }}/mypy-output.txt
+            exit $mypy_exit
+          fi
+          cat ${{ runner.temp }}/mypy-output.txt | mypy-baseline filter --hide-stats > ${{ runner.temp }}/mypy-baselined-output.txt || baseline_exit=$?
+          echo running reviewdog again for mypy
+          reviewdog -f=mypy -name=mypy -filter-mode=nofilter $REVIEWDOG_ARGS < ${{ runner.temp }}/mypy-baselined-output.txt
 
       - name: Run reviewdog for PR
         if: github.event_name == 'pull_request'
